---
title: "Regilaul: Vowel Spatial and Temporal Models"
output: html_notebook
---
```{r}
library(lme4)
library(tidyverse)
library(ggplot2)
library(phonR)

regi_df = read.csv("regi_tidy.csv")
```

```{r}
#make sure categorical values read as characters instead of integers
regi_df$foot <- as.character(regi_df$foot)
regi_df$quantity <- as.character((regi_df$quantity))
regi_df$stressed <- as.character(regi_df$stressed)
regi_df$song <- as.character(regi_df$song)



```

```{r}
summary(regi_df)
```

```{r}
boxplot(duration~stressed+ictus,data= regi_df,
        col=c("pink","grey"))

```
```{r}
boxplot(duration~stressed + ictus, data = regi_df, col = c("violet","gold","green","blue","pink","grey"))
```
```{r}
chisq.test(regi_df$ictus,regi_df$stressed, correct = FALSE)
chisq.test(regi_df$ictus,regi_df$quantity, correct = FALSE)

```

```{r}
interaction.plot(regi_df$ictus,regi_df$quantity, regi_df$duration)
```
```{r}
interaction.plot(regi_df$stressed,regi_df$ictus, regi_df$duration)


```



```{r}
mdl = lmer(duration~stressed + ictus + quantity + ictus*stressed + ictus*quantity+ (1|performer)+(1|song)+(1|word),data = regi_df,REML=FALSE)
summary(mdl)


```
```{r}
isSingular(mdl)
```

```{r}
hist(residuals(mdl))
```
```{r}
qqnorm(residuals(mdl))
```
```{r}
regi_df$fit <- predict(mdl)
```

```{r}
durplot <- ggplot(regi_df,aes(stressed, duration,group=interaction(stressed,ictus),col=stressed,shape=ictus)) + facet_grid(vars(ictus),vars(performer)) +geom_violin()+geom_jitter(alpha=0.3)

```
```{r}
plot(durplot)
```
```{r}
durplot_str <- ggplot(stress_df,aes(quantity, duration,group=interaction(ictus,quantity),col=quantity,shape=ictus)) + facet_grid(vars(ictus),vars(performer)) +geom_violin(alpha=0.05) + geom_jitter(alpha=0.3)
plot(durplot_str)
```
```{r}
durplot_un <- ggplot(unastress_df,aes(quantity, duration,group=interaction(ictus,quantity),col=quantity,shape=ictus)) + facet_grid(vars(ictus),vars(performer)) +geom_violin(alpha=0.05) + geom_jitter(alpha=0.3)
plot(durplot_un)
```


```{r}

stress_df = filter(regi_df,stressed=="1",performer != "LO")
unstress_df = filter(regi_df,stressed=="0")
qmdl <- lmer(duration~quantity *ictus+(1|performer)+(1|word),data=stress_df,REML=FALSE)
summary(qmdl)
```

```{r}
anova(qmdl)
#drop1(qmdl,test="Chisq")
```
```{r}
dropped <- update(mdl,.~.-stressed:ictus)
summary(dropped)
```
```{r}
anova(dropped)
```

```{r}
mdlN <- lmer(duration~ (1|performer) +(1|word), data = regi_df, REML = FALSE)
summary(mdlN)
#anova(mdlN)
```

```{r}
anova(mdl,mdlN)
```

```{r}
drop1(mdl,test="Chisq")
```

```{r}
mdlX <- lmer(duration~ictus + stressed + (1+ictus|quantity)+ (1|performer) +(1|word),data = regi_df,REML=FALSE)
summary(mdlX)
anova(mdlX,mdl)
```
```{r}
anova(mdlX)
```

```{r}
drop1(mdlX,test="Chisq")
```

```{r}
mdlXn <- lmer(duration~(1|performer) +(1|word),data = regi_df,REML=FALSE)
anova(mdlXn,mdlX)
```

```{r}
coef(mdlX)$performer
#plot(fitted(mdlX),residuals(mdlX))

```

```
