---
title: "Quantity and Ictus Duration & space"
output: html_notebook
---

```{r}
library("sjPlot")
library("lme4")
library("ggplot2")
library("broom")
library("dplyr")
library("ggpattern")
quant_df <- read.csv("vowel_master.csv", header= TRUE)
quant_df$ictus <- as.factor(quant_df$ictus)
quant_df$stressed <- as.factor(quant_df$stressed)
quant_df$stressed <- recode_factor(quant_df$stressed, "0" = "unstressed","1" = "stressed")
quant_df$quantity <- as.factor(quant_df$quantity)
quant_df$song <- as.factor(quant_df$song)
quant_df$word <- as.factor(quant_df$word)
quant_df$shape <- as.factor(quant_df$shape)
head(quant_df)
```

```{r}
quant_data <- filter(quant_df, quant_df$stressed == "stressed")
quant_data
```

```{r}
ggplot(quant_data,aes(quantity, duration, pattern = quantity)) + 
  #geom_violin()+
  geom_boxplot_pattern(alpha = 0.3) +
  #geom_jitter(alpha = 0.5) +
  labs(x = "syllable quantity", y = "mean vowel duration(s)", title = "temporal effects of beat position on vowel nuclei of stressed syllables", subtitle = "in three contrastive quantities") + 
  facet_wrap("ictus") + 
  theme_classic()
ggsave("q_dur.png")


```

```{r}
maxmdl <- lmer(duration ~ quantity + ictus + quantity*ictus + (1|song)+ (1|syll) +(1|shape)+ (1|word)+ (1|performer), data = quant_data, REML = FALSE)
summary(maxmdl)
```

```{r}
tab_model(maxmdl, digits.re = 4)
```

```{r}
nullmdl <- lmer(duration ~(1|song)+ (1|syll) +(1|shape)+ (1|word)+ (1|performer) , data = quant_data, REML = FALSE)
summary(nullmdl)
```

```{r}
tab_model(nullmdl, digits.re = 4)
```

```{r}
comp_quant <- anova(maxmdl, nullmdl)
print(comp_quant)

```

```{r}
plot(maxmdl)
```
