---
title: "Q1 and Q2 duration in stress and ictus"
output: html_notebook
---

```{r}
library("lme4")
library("ggplot2")
library("broom")
library("dplyr")
data_df <- read.csv("vowel_master.csv", header= TRUE)


data_df$ictus <- as.factor(data_df$ictus)
data_df$stressed <- as.factor(data_df$stressed)
data_df$stressed <- recode_factor(data_df$stressed, "0" = "unstressed","1" = "stressed")
data_df$quantity <- as.factor(data_df$quantity)
data_df$song <- as.factor(data_df$song)
data_df$word <- as.factor(data_df$word)
#head(data_df)

#to look at vowel duration in song-level and word-level prominence positions, I filter out only syllables of Q1 and Q2, and only those shapes which surface in both stressed and unstressed positions 
strictus_data <- filter(data_df, data_df$quantity!="3" & data_df$shape != "VCC" & data_df$shape != "VVC" & data_df$shape != "VV")

#strictus_data <- filter(strictus_data, nchar(strictus_data$segment)==1)
head(strictus_data)


```

```{r}
ggplot(strictus_data,aes(ictus,duration)) + 
  geom_jitter(color = "violet", alpha = 0.5) +
  facet_wrap("song") +
  labs(x = "beat position", y = "mean vowel duration (ms)") + 
  theme_minimal()
ggsave("song_icK_dur.png")
  
ggplot(strictus_data,aes(stressed,duration)) + 
  geom_jitter(color = "orange", alpha = 0.5) +
  facet_wrap("song") + 
  labs(x = "word stress", y = "within-song mean vowel duration (ms)") + 
  theme_minimal()
ggsave("song_str_dur.png")

ggplot(strictus_data,aes(ictus,duration)) + 
  geom_jitter(color = "violet", alpha = 0.5) +
  facet_wrap("performer") + 
  labs(x = "beat position", y = "mean vowel duration (ms)") + 
  theme_minimal()
ggsave("perf_ick_dur.png")
ggplot(strictus_data,aes(stressed,duration)) + 
  geom_jitter(color = "orange", alpha = 0.5) +
  facet_wrap("performer") + 
  labs(x = "word stress", y = "within-subject mean vowel duration (ms)") + 
  theme_minimal()
ggsave("perf_str_dur.png")
```

```{r}
interaction.plot(strictus_data$quantity,strictus_data$ictus,strictus_data$duration,xlab="quantity",ylab="mean vowel duration(ms)",trace.label = "beat")
```

```{r}
interaction.plot(strictus_data$stressed,strictus_data$ictus,strictus_data$duration,xlab="stressed",ylab="mean vowel duration(ms)",trace.label = "beat")
```

```{r}
ggplot(strictus_data,aes(x=stressed ,y=duration,color = ictus)) + 
  geom_violin() + stat_ydensity() + theme_minimal() +
  labs( xlab = "word stress" ,ylab = "vowel duration (ms)") + 
  facet_wrap("quantity", labeller = label_both)
  
ggsave("dur_density_qfac.png")


```

```{r}
ggplot(strictus_data,aes(x=shape,y=duration, color = ictus)) +
geom_violin() + stat_ydensity() + theme_minimal() +
labs( xlab = "syllable shape" ,ylab = "vowel duration (ms)") 

ggsave("dur_shapeictus.png")
```

```{r}
ggplot(strictus_data,aes(x=shape,y=duration, color = stressed)) +
geom_violin() + stat_ydensity() + theme_minimal() +
labs( xlab = "syllable shape" ,ylab = "vowel duration (ms)") 

ggsave("dur_shapestress.png")
```

```{r}
lindesignmod <- lmer(duration ~ ictus + stressed + ictus*stressed + quantity+  (1|song) + (1|performer), data = strictus_data, REML = FALSE)
summary(lindesignmod)
```

```{r}
plot(lindesignmod)
```

```{r}
linperfmod <- lmer(duration ~ ictus + stressed + ictus*stressed  + quantity + (1|performer), data = strictus_data,REML = FALSE)
summary(linperfmod)
```

```{r}
linsongmod <- lmer(duration ~ ictus + stressed + ictus*stressed + quantity + (1|song), data = strictus_data,REML = FALSE)
summary(linsongmod)
```

```{r}
linnullIntmod <- lmer(duration ~ (1|song) + (1|performer), data = strictus_data, REML = FALSE)
n1 <- summary(linnullIntmod)
print(n1)
```

```{r}
compp <- anova(lindesignmod,linsongmod)
print(compp)
```

```{r}
comps <- anova(lindesignmod,linperfmod)
print(comps)
```

```{r}
comp2 <- anova(lindesignmod,linnullIntmod)
print(comp2)
```

```{r}
comp3 <- anova(linsongmod,linnullIntmod)
print(comp3)
```

```{r}

ggplot(strictus_data,aes(ictus,euclid)) + 
  geom_jitter(color = "violet", alpha = 0.5) +
  facet_wrap("song") +
  labs(x = "beat position", y = "vowel dispersion") + 
  theme_minimal()
ggplot(strictus_data,aes(stressed,euclid)) + 
  geom_jitter(color = "orange", alpha = 0.5) +
  facet_wrap("song") +
  labs(x = "word stress", y = "vowel dispersion") + 
  theme_minimal()
ggplot(strictus_data,aes(ictus,euclid)) + 
  geom_jitter(color = "violet", alpha = 0.5) +
  facet_wrap("performer") +
  labs(x = "beat position", y = "vowel dispersion") + 
  theme_minimal()
ggplot(strictus_data,aes(stressed,euclid)) + 
  geom_jitter(color = "orange", alpha = 0.5) +
  facet_wrap("performer") +
  labs(x = "word stress", y = "vowel dispersion") + 
  theme_minimal()
  

```

```{r}
ggplot(strictus_data,aes(x=ictus ,y=euclid,color = ictus)) + 
  geom_violin() + stat_ydensity() + theme_minimal() +
  labs( xlab = "beat" ,ylab = "euclidean distance") 
  #facet_wrap("quantity", labeller = label_both)
```

```{r}
interaction.plot(strictus_data$stressed,strictus_data$ictus,strictus_data$euclid,xlab="word stress",ylab="vowel dispersion",trace.label = "beat")
```

```{r}
interaction.plot(strictus_data$quantity,strictus_data$ictus,strictus_data$euclid,xlab="syllable quantity",ylab="vowel dispersion",trace.label = "beat")
```

```{r}
ggplot(strictus_data,aes(x=stressed ,y=euclid)) + 
  geom_violin() + stat_ydensity() + theme_minimal() +
  labs( xlab = "word stress" ,ylab = "euclidean distance") 
```

```{r}
ggplot(strictus_data,aes(x=quantity ,y=euclid)) + 
  geom_violin() + stat_ydensity() + theme_minimal() +
  labs( xlab = "syllable quantity" ,ylab = "euclidean distance") 
```
